#ifndef TINGLE_GAME_PHASE_SCRIPT_VM_H
#define TINGLE_GAME_PHASE_SCRIPT_VM_H

#include "tingle/types.h"

/* Compact bytecode interpreter state with registers and a shared value/call stack. */
typedef struct GamePhaseScriptVm {
    const void *vtable;
    const s8 *cursor;
    const s8 *scriptStart;
    void *callbacks_0c[8];
    u32 registers[8];
    u32 stack[12];
    s8 stackDepth;
    u8 stateFlags;
    s8 field_7e;
    s8 field_7f;
    void *context;
} GamePhaseScriptVm;

/* Script VM specialization used by actor-bound phase scripts. */
typedef struct GamePhaseActorScriptVm {
    GamePhaseScriptVm base;
    void *actor;
    s32 waitCounter;
    u32 flags_8c;
    u8 value_90;
    u8 padding_91[3];
} GamePhaseActorScriptVm;

#ifdef __cplusplus
extern "C" {
#endif
GamePhaseScriptVm *GamePhaseScriptVm_Init(GamePhaseScriptVm *self);
void GamePhaseScriptVm_Reset(GamePhaseScriptVm *self);
GamePhaseScriptVm *GamePhaseScriptVm_Destroy(GamePhaseScriptVm *self);
GamePhaseScriptVm *GamePhaseScriptVm_DestroyAndFree(GamePhaseScriptVm *self);
GamePhaseScriptVm *GamePhaseScriptVm_DestroyBase(GamePhaseScriptVm *self);
GamePhaseScriptVm *GamePhaseScriptVm_InitWithScript(GamePhaseScriptVm *self,
                                                    const s8 *script,
                                                    void *context);
void GamePhaseScriptVm_ResetWithScript(GamePhaseScriptVm *self,
                                       const s8 *script, void *context);
GamePhaseScriptVm *GamePhaseScriptVm_Assign(GamePhaseScriptVm *self,
                                            const GamePhaseScriptVm *source);
void GamePhaseScriptVm_CopyState(GamePhaseScriptVm *self,
                                 const GamePhaseScriptVm *source);
u32 GamePhaseScriptVm_Pop(GamePhaseScriptVm *self);
void GamePhaseScriptVm_Push(GamePhaseScriptVm *self, u32 value);
s32 GamePhaseScriptVm_Execute(GamePhaseScriptVm *self, s32 singleStep);
s32 func_020127f0(GamePhaseScriptVm *self);
void GamePhaseScriptVm_SetResult(GamePhaseScriptVm *self, u32 value);
s32 func_02012814(GamePhaseScriptVm *self);
s32 func_02012a60(GamePhaseScriptVm *self);
s32 func_02012a8c(GamePhaseActorScriptVm *self);
s32 func_02012afc(GamePhaseActorScriptVm *self);
s32 func_02012c14(GamePhaseActorScriptVm *self);
s32 func_02012c34(GamePhaseActorScriptVm *self);
s32 func_02012c98(GamePhaseActorScriptVm *self);
s32 func_02012cb0(GamePhaseActorScriptVm *self);
s32 func_02012cd4(GamePhaseActorScriptVm *self);
s32 func_02012d00(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_LookupAngleFirstComponent(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_LookupAngleSecondComponent(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ComputeAngle(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetVectorX(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetVectorY(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetVectorZ(GamePhaseActorScriptVm *self);
s32 func_02012e98(GamePhaseActorScriptVm *self);
s32 func_02012f40(GamePhaseActorScriptVm *self);
s32 func_02012f64(GamePhaseActorScriptVm *self);
s32 func_02013014(GamePhaseActorScriptVm *self);
s32 func_02013030(GamePhaseActorScriptVm *self);
s32 func_02013074(GamePhaseActorScriptVm *self);
s32 func_02013094(GamePhaseActorScriptVm *self);
s32 func_020130c0(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartMovement(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_WaitForMovementCompletion(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_IsMovementActive(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetField5cLowHalfword(GamePhaseActorScriptVm *self);
s32 func_0201350c(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetField3c(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetField40(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_LookupDirectionTowardCoordinates(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetCollection1ActorVectorX(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetCollection1ActorVectorY(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetCollection1ActorVectorZ(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetActorFlag10AndAttachmentFlag40(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetAttachmentFlag80(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetAttachmentFlag20(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ComputeFixedPointRoot(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_CancelMovement(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_FaceIndexedActorAndGetAttachmentByte38(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetFieldE6(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ClearFlag01000000AndCleanup(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_NoOp(GamePhaseActorScriptVm *self);
s32 func_020139d8(GamePhaseActorScriptVm *self);
s32 func_02013a04(GamePhaseActorScriptVm *self);
s32 func_02013a34(GamePhaseActorScriptVm *self);
s32 func_02013a7c(GamePhaseActorScriptVm *self);
s32 func_02013ac8(GamePhaseActorScriptVm *self);
s32 func_02013b74(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetGameWorkFlag(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ClearGameWorkFlag(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_TestGameWorkFlag(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ConfigureAttachmentByte3aAndFlag80(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetActorField4e(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_MaskValueByBit(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetActorFlag8(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetActorFlag200000Inverse(GamePhaseActorScriptVm *self);
void Actor_SetFlag200000Inverse(void *actor, s32 enabled);
s32 func_02013e14(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_QueryTerrainHeight(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_DiscardValue(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SavePrimaryAttachmentState(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_RestorePrimaryAttachmentState(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetValue90AndFlag2(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ClearFlag2(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ConfigureOrSpawnOverlay62Effect(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetPositionFromCoordinates(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_TranslateSecondaryBounds(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_TranslateCollisionBounds(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StageAreaRequest(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartBrightnessTransition(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_IsBrightnessTransitionPending(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetCollectionPendingValue(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_PresentationNoOp(GamePhaseActorScriptVm *self);
s32 func_020142f4(GamePhaseActorScriptVm *self);
s32 func_02014314(GamePhaseActorScriptVm *self);
s32 func_0201433c(GamePhaseActorScriptVm *self);
s32 func_020143a8(GamePhaseActorScriptVm *self);
u32 *func_02015548(u32 *result, s32 left, s32 top, s32 right, s32 bottom);
s32 GamePhaseActorScriptVm_SetMotionProbeScale(GamePhaseActorScriptVm *self);
s32 func_02015580(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_CalculateDistanceToCoordinates(GamePhaseActorScriptVm *self);
s32 func_02015610(GamePhaseActorScriptVm *self);
s32 func_02015690(GamePhaseActorScriptVm *self);
s32 func_020156c8(GamePhaseActorScriptVm *self);
s32 func_020156fc(GamePhaseActorScriptVm *self);
s32 func_0201579c(GamePhaseActorScriptVm *self);
s32 func_02015818(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetDataTableRecordByte(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_HasDataTableValue(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_UpdateDataTableValue(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetActorRectangle(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ExpandActorRectangleLeft(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ExpandActorRectangleTop(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ExpandActorRectangleRight(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ExpandActorRectangleBottom(GamePhaseActorScriptVm *self);
s32 func_02015b64(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetInteractionDirectionAndMagnitude(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_CalculateScaledDistance(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_CreateApplyScene(GamePhaseActorScriptVm *self);
s32 func_02015e40(GamePhaseActorScriptVm *self);
s32 func_02015e64(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetIndexedActorActive(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ActivateAllActors(GamePhaseActorScriptVm *self);
s32 func_02015f50(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetSystemStateHalfword5c(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StepActorOrientation(GamePhaseActorScriptVm *self);
s32 func_02016070(GamePhaseActorScriptVm *self);
s32 func_020160b0(GamePhaseActorScriptVm *self);
s32 func_020160f0(GamePhaseActorScriptVm *self);
s32 func_02016144(GamePhaseActorScriptVm *self);
s32 func_0201616c(GamePhaseActorScriptVm *self);
s32 func_020161ac(GamePhaseActorScriptVm *self);
s32 func_020161f4(GamePhaseActorScriptVm *self);
s32 func_02016238(GamePhaseActorScriptVm *self);
s32 func_02016814(GamePhaseActorScriptVm *self);
s32 func_02016898(GamePhaseActorScriptVm *self);
s32 func_020168a0(GamePhaseActorScriptVm *self);
s32 func_020168a8(GamePhaseActorScriptVm *self);
s32 func_020168d0(GamePhaseActorScriptVm *self);
s32 func_02016930(GamePhaseActorScriptVm *self);
s32 func_02016a84(GamePhaseActorScriptVm *self);
s32 func_02016bc0(GamePhaseActorScriptVm *self);
s32 func_02016c7c(GamePhaseActorScriptVm *self);
s32 func_02016d60(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_IsCollection1ActorInRectangle(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ConfigureMotionProbe(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_ResetMotionProbe(GamePhaseActorScriptVm *self);
s32 func_02017008(GamePhaseActorScriptVm *self);
s32 func_02017058(GamePhaseActorScriptVm *self);
s32 func_0201707c(GamePhaseActorScriptVm *self);
s32 func_020170cc(GamePhaseActorScriptVm *self);
s32 func_020170f0(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_AddCurrency(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetCurrency(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetCurrencyHudVisibleAndPosition(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetCurrency(GamePhaseActorScriptVm *self);
s32 func_020171f0(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartMainBrightnessToZero(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartMainBrightnessToMinus8(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartSubBrightnessToZero(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_StartSubBrightnessToMinus8(GamePhaseActorScriptVm *self);
s32 func_02017414(GamePhaseActorScriptVm *self);
s32 func_0201741c(GamePhaseActorScriptVm *self);
s32 func_02017450(GamePhaseActorScriptVm *self);
s32 func_020174dc(GamePhaseActorScriptVm *self);
s32 func_02017540(GamePhaseActorScriptVm *self);
s32 func_02017638(GamePhaseActorScriptVm *self);
s32 func_02017668(GamePhaseActorScriptVm *self);
s32 func_02017694(GamePhaseActorScriptVm *self);
s32 func_020176c8(GamePhaseActorScriptVm *self);
s32 func_020176ec(GamePhaseActorScriptVm *self);
s32 func_02017710(GamePhaseActorScriptVm *self);
s32 func_02017718(GamePhaseActorScriptVm *self);
s32 func_02017750(GamePhaseActorScriptVm *self);
s32 func_02017788(GamePhaseActorScriptVm *self);
s32 func_020177c8(GamePhaseActorScriptVm *self);
s32 func_02017818(GamePhaseActorScriptVm *self);
s32 func_0201787c(GamePhaseActorScriptVm *self);
s32 func_020178bc(GamePhaseActorScriptVm *self);
s32 func_020178fc(GamePhaseActorScriptVm *self);
s32 func_02017938(GamePhaseActorScriptVm *self);
s32 func_0201797c(GamePhaseActorScriptVm *self);
s32 func_02017a54(GamePhaseActorScriptVm *self);
s32 func_02017ac8(GamePhaseActorScriptVm *self);
s32 func_02017d1c(GamePhaseActorScriptVm *self);
s32 func_02018208(GamePhaseActorScriptVm *self);
s32 func_020184d4(GamePhaseActorScriptVm *self);
s32 func_02018504(GamePhaseActorScriptVm *self);
s32 func_0201850c(GamePhaseActorScriptVm *self);
s32 func_0201853c(GamePhaseActorScriptVm *self);
s32 func_0201856c(GamePhaseActorScriptVm *self);
s32 func_020185f4(GamePhaseActorScriptVm *self);
s32 func_0201863c(GamePhaseActorScriptVm *self);
s32 func_020189e4(GamePhaseActorScriptVm *self);
s32 func_02018c14(GamePhaseActorScriptVm *self);
s32 func_02018c3c(GamePhaseActorScriptVm *self);
s32 func_02018f10(GamePhaseActorScriptVm *self);
s32 func_02019104(GamePhaseActorScriptVm *self);
s32 func_02019128(GamePhaseActorScriptVm *self);
s32 func_02019164(GamePhaseActorScriptVm *self);
s32 func_0201918c(GamePhaseActorScriptVm *self);
s32 func_020191c4(GamePhaseActorScriptVm *self);
s32 func_02019288(GamePhaseActorScriptVm *self);
s32 func_020192a8(GamePhaseActorScriptVm *self);
s32 func_020192cc(GamePhaseActorScriptVm *self);
s32 func_020192ec(GamePhaseActorScriptVm *self);
s32 func_020192f4(GamePhaseActorScriptVm *self);
s32 func_0201939c(GamePhaseActorScriptVm *self);
s32 func_020198d0(GamePhaseActorScriptVm *self);
s32 func_02019978(GamePhaseActorScriptVm *self);
s32 func_0201999c(GamePhaseActorScriptVm *self);
s32 func_020199cc(GamePhaseActorScriptVm *self);
s32 func_02019a10(GamePhaseActorScriptVm *self);
s32 func_02019a44(GamePhaseActorScriptVm *self);
s32 func_02019a6c(GamePhaseActorScriptVm *self);
s32 func_02019aa4(GamePhaseActorScriptVm *self);
s32 func_02019c60(GamePhaseActorScriptVm *self);
s32 func_02019dd4(GamePhaseActorScriptVm *self);
s32 func_02019f4c(GamePhaseActorScriptVm *self);
s32 func_02019f6c(GamePhaseActorScriptVm *self);
s32 func_02019f8c(GamePhaseActorScriptVm *self);
s32 func_0201a00c(GamePhaseActorScriptVm *self);
s32 func_0201a03c(GamePhaseActorScriptVm *self);
s32 func_0201a090(GamePhaseActorScriptVm *self);
s32 func_0201a130(GamePhaseActorScriptVm *self);
s32 func_0201a1f0(GamePhaseActorScriptVm *self);
s32 func_0201a304(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GenerateModeBasedValue(GamePhaseActorScriptVm *self);
s32 func_0201a50c(GamePhaseActorScriptVm *self);
s32 func_0201a540(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_DispatchSoundContextUtilityCommand(GamePhaseActorScriptVm *self);
s32 func_0201a614(GamePhaseActorScriptVm *self);
s32 func_0201a938(GamePhaseActorScriptVm *self);
s32 func_0201aa14(GamePhaseActorScriptVm *self);
s32 func_0201ab60(GamePhaseActorScriptVm *self);
s32 func_0201ac18(GamePhaseActorScriptVm *self);
s32 func_0201ac9c(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetPackedBitGridMask(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetPackedBitGridBit(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_IsPointInRectangle(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetActiveEntityPositionX(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetActiveEntityPositionY(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetActiveEntityPositionZ(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SetPlacementModeAndSynchronize(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_QueryGlobalContextByIndex(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_CalculateScaledRuntimeValue(GamePhaseActorScriptVm *self);
s32 func_0201b040(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_GetOneBasedPhaseRecordByte4c(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_SendCommand2aToCollection2Actor0(GamePhaseActorScriptVm *self);
s32 func_0201b0d4(GamePhaseActorScriptVm *self);
GamePhaseActorScriptVm *GamePhaseActorScriptVm_Init(GamePhaseActorScriptVm *self);
GamePhaseActorScriptVm *GamePhaseActorScriptVm_InitWithScript(
    GamePhaseActorScriptVm *self, void *actor, const s8 *script,
    void *context);
void GamePhaseActorScriptVm_ResetState(GamePhaseActorScriptVm *self);
GamePhaseActorScriptVm *GamePhaseActorScriptVm_Assign(
    GamePhaseActorScriptVm *self, const GamePhaseActorScriptVm *source);
void GamePhaseActorScriptVm_CopyState(GamePhaseActorScriptVm *self,
                                      const GamePhaseActorScriptVm *source);
GamePhaseActorScriptVm *GamePhaseActorScriptVm_Destroy(
    GamePhaseActorScriptVm *self);
GamePhaseActorScriptVm *GamePhaseActorScriptVm_DestroyAndFree(
    GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_DispatchOpcode(GamePhaseActorScriptVm *self, s32 index);
void GamePhaseActorScriptVm_Activate(GamePhaseActorScriptVm *self);
s32 GamePhaseActorScriptVm_IsActive(const GamePhaseActorScriptVm *self);
s32 GamePhaseScriptVm_ReadS16Le(const s8 *bytes);
u32 GamePhaseScriptVm_ReadU32Le(const s8 *bytes);
void GamePhaseScriptVm_UpdateZeroFlag(GamePhaseScriptVm *self, s32 index);
s32 GamePhaseScriptVm_Halt(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_JumpAndYield(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_Jump(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CopyRegister(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_LoadRegisterFromContext(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_StoreRegisterToContext(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushRegister(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushImmediateS16(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_LoadImmediateU32(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_AddRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_AddImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_SubtractRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_SubtractImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_MultiplyRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_MultiplyImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_DivideRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_DivideImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_ModuloRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_ModuloImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_AndRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_AndImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_OrRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_OrImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_XorRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_XorImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_NotRegister(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_JumpIfConditionSet(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_JumpIfConditionClear(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_InvokeByteMethod(GamePhaseScriptVm *self);
s32 func_0201b9a8(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareGreaterRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareGreaterEqualRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareEqualRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareLessEqualRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareLessRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareNotEqualRegisters(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareGreaterImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareGreaterEqualImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareEqualImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareLessEqualImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareLessImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_CompareNotEqualImmediate(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_Call(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_Return(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_StoreRegisterToGameWorkHalfword(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_StoreRegisterToContextSlot(GamePhaseScriptVm *self);
s32 func_0201bf04(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_LoadRegisterFromGameWorkHalfword(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_LoadRegisterFromContextSlot(GamePhaseScriptVm *self);
s32 func_0201bfb8(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushImmediateU32(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushGameWorkHalfword(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushContextSlot(GamePhaseScriptVm *self);
s32 func_0201c07c(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_StoreRegisterToGameWorkWord(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_LoadRegisterFromGameWorkWord(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushGameWorkWord(GamePhaseScriptVm *self);
s32 GamePhaseScriptVm_PushZero(GamePhaseScriptVm *self);
#ifdef __cplusplus
}
#endif

#endif
