[CmdletBinding()]
param(
    [string]$Mwccarm = $env:MWCCARM,
    [string]$Mwldarm = $env:MWLDARM,
    [string]$MwccarmRoot = $env:MWCCARM_ROOT,
    [string]$DsdExe = $env:DSD_EXE,
    [string]$ObjdiffExe = $env:OBJDIFF_EXE,
    [string]$PythonExe = $env:PYTHON_EXE
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-Executable {
    param(
        [string]$Value,
        [string]$Command,
        [string]$Fallback,
        [string]$Description
    )

    if ($Value) {
        if (-not (Test-Path -LiteralPath $Value -PathType Leaf)) {
            throw "$Description was not found: $Value"
        }
        return (Resolve-Path -LiteralPath $Value).Path
    }

    $Found = Get-Command $Command -ErrorAction SilentlyContinue
    if ($Found) {
        return $Found.Source
    }

    if ($Fallback -and (Test-Path -LiteralPath $Fallback -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $Fallback).Path
    }

    throw "$Description was not found. Pass its path or set the corresponding environment variable."
}

if ($MwccarmRoot) {
    if (-not $Mwccarm) { $Mwccarm = Join-Path $MwccarmRoot 'mwccarm.exe' }
    if (-not $Mwldarm) { $Mwldarm = Join-Path $MwccarmRoot 'mwldarm.exe' }
}

$Mwccarm = Resolve-Executable $Mwccarm 'mwccarm' 'E:\Stuff\Decomp\mwccarm\2.0\base\mwccarm.exe' 'MWCCARM'
$Mwldarm = Resolve-Executable $Mwldarm 'mwldarm' 'E:\Stuff\Decomp\mwccarm\2.0\base\mwldarm.exe' 'MWLDARM'
$DsdExe = Resolve-Executable $DsdExe 'dsd' 'E:\Stuff\Decomp\dsd.exe' 'dsd'
$ObjdiffExe = Resolve-Executable $ObjdiffExe 'objdiff-cli' 'E:\Stuff\Decomp\objdiff-cli.exe' 'objdiff-cli'
$PythonExe = Resolve-Executable $PythonExe 'python' $null 'Python'
$null = Resolve-Executable $null 'ninja' $null 'Ninja'

function ConvertTo-NinjaPath([string]$Path) {
    return $Path.Replace('$', '$$').Replace('\', '/')
}

$BuildDir = Join-Path $RepoRoot 'build'
$Directories = @(
    $BuildDir,
    (Join-Path $BuildDir 'decomp\src\system'),
    (Join-Path $BuildDir 'decomp\lib'),
    (Join-Path $BuildDir 'reference'),
    (Join-Path $BuildDir 'reports')
)
foreach ($Directory in $Directories) {
    $null = New-Item -ItemType Directory -Force -Path $Directory
}

$Config = @"
# Generated by tools/configure.ps1. Local tool paths stay under ignored build/.
repo_root = $(ConvertTo-NinjaPath $RepoRoot)
mwccarm = $(ConvertTo-NinjaPath $Mwccarm)
mwldarm = $(ConvertTo-NinjaPath $Mwldarm)
dsd = $(ConvertTo-NinjaPath $DsdExe)
objdiff = $(ConvertTo-NinjaPath $ObjdiffExe)
python = $(ConvertTo-NinjaPath $PythonExe)
"@

$ConfigPath = Join-Path $BuildDir 'config.ninja'
Set-Content -LiteralPath $ConfigPath -Value $Config -Encoding ascii

Write-Host "Configured Ninja with MWCCARM at $Mwccarm"
Write-Host "Configured Ninja with MWLDARM at $Mwldarm"
Write-Host 'Run `ninja match` to compile, extract references, compare, and verify the MT19937 unit.'
